[package]
name = "r18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mod_use = "0.2"
once_cell = "1.16"
dynfmt = { version = "0.1.5", default-features = false, features = ["curly"] }
sys-locale = "0.2"

proc-macros = { path = "./proc-macros" }

[workspace]
members = [
    "example",
    "proc-macros",
    "trans-support"
]
