[package]
name = "r18-trans-support"
version = "0.1.0"
edition = "2021"
description = "r18 translation support"
license = "MIT"
repository = "https://github.com/Limit-IM/r18"
readme = "../README.md"
authors = [
    "ho229v3666@gmail.com",
]

[dependencies]
serde = "1.0"
serde_json = "1.0"
