name: Rust

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    types:
      - review_requested
      - ready_for_review
      - opened
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --workspace -- --test-threads=1 --nocapture
